create table if not exists public.daily_health_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  log_date date not null,
  water_count integer not null default 0 check (water_count between 0 and 8),
  mood integer not null default 2 check (mood between 0 and 4),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, log_date)
);

create table if not exists public.symptom_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) > 0),
  severity text not null check (severity in ('Mild', 'Moderate', 'Severe')),
  category text not null,
  log_date date not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.daily_health_logs enable row level security;
alter table public.symptom_logs enable row level security;

drop policy if exists "Users can read their own daily health logs" on public.daily_health_logs;
create policy "Users can read their own daily health logs"
on public.daily_health_logs for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can create their own daily health logs" on public.daily_health_logs;
create policy "Users can create their own daily health logs"
on public.daily_health_logs for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own daily health logs" on public.daily_health_logs;
create policy "Users can update their own daily health logs"
on public.daily_health_logs for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can read their own symptom logs" on public.symptom_logs;
create policy "Users can read their own symptom logs"
on public.symptom_logs for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can create their own symptom logs" on public.symptom_logs;
create policy "Users can create their own symptom logs"
on public.symptom_logs for insert to authenticated
with check ((select auth.uid()) = user_id);

create index if not exists daily_health_logs_user_date_idx
on public.daily_health_logs (user_id, log_date desc);
create index if not exists symptom_logs_user_date_idx
on public.symptom_logs (user_id, log_date desc, created_at desc);
